version: '3.7'
services:
  db:
    ports:
      - 5432:5432

  api:
    ports:
      - 8002:8000
    environment:
      PRODUCTION: 'false'
      SECRET_KEY: 'yvbny6$$o6hsz4vj84wt145vx*$$^o5n!@7s0)k!0t*-oe-__mgo'
      SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: '810585960469-6t1dll32bf956ib0ia1q34kvncrr0m98.apps.googleusercontent.com'
      SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: 'Z-pUb4AqdiFz15rPLlUEmINb'

  web:
    ports:
      - 8001:8000
    build:
      args:
        PRODUCTION: 'false'
        BACKEND_URL: '//localhost:8000/api/'
        GOOGLE_CLIENT_ID: '810585960469-6t1dll32bf956ib0ia1q34kvncrr0m98.apps.googleusercontent.com'
        API_CLIENT_ID: 'AeHpsZrOk4pJxSzRCx6OV6k9HSU4M9q2QfM4EqAs'
        API_CLIENT_SECRET: '5M7qczd8UvuQA58rerF5rwAFrrezGyiNG4NwEDj7pxXjJX0fZwPIq7xS1OSyOaGqhrvnoVloyOW7FkcVdqwnB6F3aQXfgZ9yGZ82NIzKLjRrlit9ed3wgwL3UOjKBLGd'
        GOOGLE_ANALYTICS_ID: 'UA-18174506-2'

  nginx:
    ports:
      - 8080:8080
