version: '3.7'
services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  api:
    build: .
    image: kos33rd/ac-friends-api
    command: /app/run.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      PORT: '8000'
    depends_on:
      - db
    links:
      - db

  web:
    build: ./web
    image: kos33rd/ac-friends-web
    ports:
      - 8001:8000

  nginx:
    build: ./nginx
    image: kos33rd/ac-friends-nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - api
    links:
      - web
      - api

volumes:
  postgres_data:
