version: '3.7'
services:
  db:
    ports:
      - 5432:5432

  api:
    ports:
      - 8002:8000
    environment:
      PRODUCTION: 'false'

  web:
    ports:
      - 8001:8000
    build:
      args:
        PRODUCTION: 'false'
        BACKEND_URL: '//localhost:8000/'

  nginx:
    ports:
      - 8080:8080
