version: '3.7'
services:

  api:
    environment:
      PRODUCTION: 'true'

  web:
    build:
      args:
        PRODUCTION: 'true'
        BACKEND_URL: '/api/'

  nginx:
    ports:
      - 8080:8080

volumes:
  postgres_data:
