version: '3.7'
services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5431:5432
  api:
    build: .
    command: /app/run.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      PORT: '8000'
    depends_on:
      - db
    links:
      - db:db
volumes:
  postgres_data:
