version: '3.7'
services:
  db:
    ports:
      - 5432:5432

  api:
    ports:
      - 8002:8000
    environment:
      PRODUCTION: 'false'
      SECRET_KEY: 'REPLACE WITH A VALUE'
      SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: 'REPLACE WITH A VALUE'
      SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: 'REPLACE WITH A VALUE'

  web:
    ports:
      - 8001:8000
    build:
      args:
        PRODUCTION: 'false'
        BACKEND_URL: '//localhost:8000/api/'

  nginx:
    ports:
      - 8080:8080
