version: '3.7'
services:

  api:
    environment:
      PRODUCTION: 'true'
      SECRET_KEY: 'REPLACE WITH A VALUE'
      SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: 'REPLACE WITH A VALUE'
      SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: 'REPLACE WITH A VALUE'

  web:
    build:
      args:
        PRODUCTION: 'true'
        BACKEND_URL: '/api/'

  nginx:
    ports:
      - 8080:8080

volumes:
  postgres_data:
