version: '3.7'
services:

  api:
    environment:
      PRODUCTION: 'true'
      SECRET_KEY: 'REPLACE WITH A GENERATED RANDOM VALUE'
      SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: 'REPLACE WITH A VALUE FROM GOOGLE API CONSOLE'
      SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: 'REPLACE WITH A VALUE FROM GOOGLE API CONSOLE'

  web:
    build:
      args:
        PRODUCTION: 'true'
        BACKEND_URL: '/api/'
        GOOGLE_CLIENT_ID: 'REPLACE WITH A VALUE FROM GOOGLE API CONSOLE'
        API_CLIENT_ID: 'REPLACE WITH A VALUE FROM API ADMIN PANEL'
        API_CLIENT_SECRET: 'REPLACE WITH A VALUE FROM API ADMIN PANEL'
        GOOGLE_ANALYTICS_ID: 'REPLACE WITH A VALUE FROM GOOGLE ANALYTICS ADMIN PANEL'

  nginx:
    ports:
      - 8080:8080

volumes:
  postgres_data:
