version: '3.7'
services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    build: .
    image: kos33rd/ac-friends-api
    command: /app/run.sh
    volumes:
      - .:/app
    environment:
      PORT: '8000'
    depends_on:
      - db
    links:
      - db

  web:
    build: ./web
    image: kos33rd/ac-friends-web

  nginx:
    build: ./nginx
    image: kos33rd/ac-friends-nginx
    depends_on:
      - web
      - api
    links:
      - web
      - api

volumes:
  postgres_data:
