# Generated by Django 3.0.4 on 2020-03-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20200329_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterModelManagers(
            name='player',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='player',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
