# Generated by Django 3.0.4 on 2020-03-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_player_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar_url',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='bump_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='commentary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='creation_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='nintendo_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
