# Generated by Django 3.0.4 on 2020-03-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20200331_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='language',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
