# Generated by Django 3.0.4 on 2020-04-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_player_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='fruits',
            field=models.ManyToManyField(related_name='player_fruits', to='player.Fruit'),
        ),
    ]
