# Generated by Django 3.0.4 on 2020-04-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_auto_20200403_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='icon',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
