# Generated by Django 3.0.4 on 2020-04-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_fruit_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='commentary',
            field=models.TextField(default=None, null=True),
        ),
    ]
