# Generated by Django 3.0.4 on 2020-04-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_auto_20200403_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='nintendo_id',
            new_name='friend_code',
        ),
    ]
