# Generated by Django 3.0.4 on 2020-04-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_auto_20200404_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playdays',
            field=models.CharField(choices=[(1, 'Every day'), (2, 'On weekends'), (3, 'On weekdays')], default=1, max_length=32),
        ),
        migrations.AddField(
            model_name='player',
            name='playtime',
            field=models.CharField(choices=[(1, 'During the day'), (2, 'In the morning'), (3, 'In the evening'), (4, 'At night'), (5, 'All day long 😵')], default=1, max_length=32),
        ),
    ]
