# Generated by Django 3.0.4 on 2020-04-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0014_auto_20200405_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
