# Generated by Django 3.0.4 on 2020-04-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_auto_20200405_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bump_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='creation_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
